apiVersion: v1
kind: ConfigMap
metadata:
  name: webhook-switch-port-client-config
  namespace: prognose
data:
  LOG_LEVEL: "INFO"
  DISABLE_HEALTHZ_LOGS: "true"
  SWITCH_HOST: "192.168.24.68"
  DEFAULT_VLAN_ID: "100"

  # Notification configuration
  NOTIFICATION_ENDPOINT: "https://prognose.crownlabs.polito.it/api/notifications/webhook"
  NOTIFICATION_TIMEOUT: "30"

  # Webhook log configuration  
  WEBHOOK_LOG_ENDPOINT: "https://prognose.crownlabs.polito.it/api/webhooks/log"
  WEBHOOK_LOG_TIMEOUT: "30"
