apiVersion: v1
kind: Secret
metadata:
  name: webhook-switch-port-client-secret
  namespace: prognose
type: Opaque
data:
  # Base64 encoded webhook secret - replace with your actual secret
  # To encode: echo -n "your-webhook-secret" | base64
  # Base64 encoded value of the secret proposed in the web-app
  WEBHOOK_SECRET: <b64-secret-value>
  
  # Network switch credentials (base64 encoded)
  # To encode: echo -n "your-switch-username" | base64
  SWITCH_USERNAME: <b64-switch-username>
  # To encode: echo -n "your-switch-password" | base64
  SWITCH_PASSWORD: <b64-switch-password>
